include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
  exclude:
    - "**/*.config.dart"
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.gr.dart"
