name: ahhhhhh
description: Makes your smartphone moan, scream or laugh when charging, discharging or full.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+19

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.17.2
  auto_route: ^0.6.9
  battery: ^1.0.11
  cupertino_icons: ^1.0.0
  equatable: ^1.2.5
  file_picker: ^2.1.5+1
  firebase_admob: ^0.11.0+1
  flutter_bloc: ^6.1.1
  flutter_launcher_icons: ^0.8.1
  flutter_swiper: ^1.1.6
  freezed_annotation: ^0.12.0
  get_it: ^5.0.4
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  image_picker: ^0.6.7+21
  injectable: ^1.0.7
  introduction_screen: ^1.0.9
  logger: ^0.9.4
  package_info: ^0.4.3+2
  path_provider: ^1.6.27
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner: ^1.10.13
  freezed: ^0.12.7
  hive_generator: ^0.8.2
  injectable_generator: ^1.0.7
  very_good_analysis: ^1.0.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher/ic_launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/audios/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: VarelaRound
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
