name: ahhhhhh
description: Makes your smartphone moan, scream or laugh when charging, discharging or full.

version: 2.3.0+26

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.19.0
  auto_route: ^2.2.0
  battery: ^2.0.3
  cupertino_icons: ^1.0.3
  equatable: ^2.0.3
  file_picker: ^3.0.2+2
  flutter_background_service: ^0.1.5
  flutter_bloc: ^7.0.1
  flutter_launcher_icons: ^0.9.0
  flutter_swiper: ^1.1.6
  freezed_annotation: ^0.14.2
  get_it: ^7.1.4
  google_mobile_ads: ^0.13.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  injectable: ^1.4.1
  introduction_screen: ^2.1.0
  logger: ^1.0.0
  package_info: ^2.0.2
  path_provider: ^2.0.2
  url_launcher: ^6.0.6

dev_dependencies:
  auto_route_generator: ^2.1.0
  build_runner: ^2.0.4
  freezed: ^0.14.2
  hive_generator: ^1.1.0
  injectable_generator: ^1.4.1
  very_good_analysis: ^2.1.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher/ic_launcher.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audios/

  fonts:
    - family: VarelaRound
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
